# Generated by Django 4.2.7 on 2023-11-21 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0002_alter_purchaseorder_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='items',
        ),
    ]
