# Generated by Django 4.2.7 on 2023-11-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0005_alter_historicalperformance_quality_rating_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='items',
            field=models.JSONField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
